CREATE DATABASE walmart_db;
USE walmart_db;

-- Find the Highest-Rated Category in Each Branch
WITH RankedCategory AS (
    SELECT 
        branch, 
        category, 
        AVG(rating) AS avg_rating,
        RANK() OVER (PARTITION BY branch ORDER BY AVG(rating) DESC) AS rnk
    FROM walmart_sales
    GROUP BY branch, category
)
SELECT branch, category, ROUND(avg_rating, 2) AS avg_rating
FROM RankedCategory
WHERE rnk = 1;

-- Identify the Busiest Day for Each Branch (Highest Transaction Count)
WITH DailySales AS (
    SELECT 
        branch, 
        DAYNAME(date) AS day_name, 
        COUNT(invoice_id) AS total_transactions,
        RANK() OVER (PARTITION BY branch ORDER BY COUNT(invoice_id) DESC) AS rnk
    FROM walmart_sales
    GROUP BY branch, DAYNAME(date)
)
SELECT branch, day_name, total_transactions
FROM DailySales
WHERE rnk = 1;

-- Determine the Most Common Payment Method per Branch
WITH BranchPayment AS (
    SELECT 
        branch, 
        payment_method, 
        COUNT(invoice_id) AS total_transactions,
        RANK() OVER (PARTITION BY branch ORDER BY COUNT(invoice_id) DESC) AS rnk
    FROM walmart_sales
    GROUP BY branch, payment_method
)
SELECT branch, payment_method, total_transactions
FROM BranchPayment
WHERE rnk = 1;

-- Calculate Total Revenue and Profit Generated by Each Category
SELECT 
    category, 
    ROUND(SUM(total), 2) AS total_revenue, 
    ROUND(SUM(profit), 2) AS total_profit
FROM walmart_sales
GROUP BY category
ORDER BY total_profit DESC;

-- Analyze Sales Volume and Revenue by Time Shift (Morning, Afternoon, Evening)
SELECT 
    shift, 
    COUNT(invoice_id) AS total_invoices, 
    ROUND(SUM(total), 2) AS total_revenue
FROM walmart_sales
GROUP BY shift
ORDER BY total_invoices DESC;